CommodityGroupIdParameter:
  name: group_id
  in: query
  schema:
    type: string
    format: uuid
  description: Filter by commodity group ID

CommodityIdParameter:
  name: commodity_id
  in: query
  schema:
    type: string
    format: uuid
  description: Filter by commodity ID

BalancesOrderingsParameter:
  name: orderings
  in: query
  schema:
    type: array
    items:
      type: string
      enum:
        - commodity_name
        - -commodity_name
        - amount
        - -amount
      description: Order by field
