PageParameter:
  name: page
  in: query
  schema:
    type: integer
    default: 1
  description: Page number for pagination

PageSizeParameter:
  name: page_size
  in: query
  schema:
    type: integer
    default: 20
  description: Number of items per page

SearchParameter:
  name: search
  in: query
  schema:
    type: string
  description: Search query
